---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Home
- type: document
  path: index.md
  label: Page principal (EN)
- type: document
  path: index_fr.md
  label: Page Principal (FR)
- type: directory
  path: collections/_posts/en
  label: Posts (EN)
  create: documents
  match: "**/*"
  templates:
  - template-post
- type: directory
  path: collections/_posts/fr
  label: Posts (FR)
  create: documents
  match: "**/*"
  templates:
  - template-post
- type: heading
  label: People ERPI
- type: directory
  path: collections/_people/en
  label: People (EN)
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_people/fr
  label: Equipe (FR)
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Projects
- type: directory
  path: collections/_projects/en
  label: Projects (EN)
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_projects/fr
  label: Projets (FR)
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - lorraine-smart-city-living-lab-f4befa28-bdf1-4daa-a16a-977895ccc509
- type: heading
  label: Publications
- type: directory
  path: collections/_publications/en
  label: Publications (EN)
  create: none
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: collections/_publications/fr
  label: Publications (FR)
  create: none
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Contact
- type: document
  path: _pages/en/contact.md
  label: Contact (EN)
  match: "**/*"
- type: document
  path: _pages/fr/contact.md
  label: Contactez-nous (FR)
  match: "**/*"
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
